version: '3'

services:
  app:
    build:
      dockerfile: ./docker/api.dockerfile
      context: .
    container_name: fastapi_graphql
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "3000", "--reload"]